# .goreleaser.yml
project_name: bqt
builds:
  - env: [CGO_ENABLED=1, CC=clang, CXX=clang++]
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    id: "bqt"
    dir: .
    main: ./cmd/bqt
